export {
  DEMO_ASSISTANT_PROMPTS,
  DEMO_DEFAULTS,
  clearStoredDemoSeedKey,
  ensureCurrentDemoSeed,
  ensureDemoAccount,
  generateDemoSeed,
  getDemoSeedKey,
  getDemoSplitwisePayload,
  getStoredDemoSeedKey,
  isDemoModeEnabled,
  isDemoModeEnabledForHost,
  isDemoUser,
  isDemoUserEmail,
  resetDemoData,
  setStoredDemoSeedKey,
} from "./demo";
